/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Tugas1;

import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author TAUFIQ
 */
public class TokoAir extends javax.swing.JFrame {

    /**
     * Creates new form no1
     */
    public TokoAir() {
        initComponents();
        conn = new Koneksi();
        tampilData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
//    -------------- Membuat ID Random --------------
    private  String generateRandString(int lenght) {
        String alphaNUM ="ABCDEFGHIJKLNMOPQRSTUVWXYZabcdefghijklnmopqrstuvwxyz0123456789";
        StringBuilder randStr = new StringBuilder();
        
        for (int i =0; i<lenght; i++){
            int ind =(int)(alphaNUM.length()*Math.random());
            randStr.append(alphaNUM.charAt(ind));
        }
        return randStr.toString();
    } 
//     ----------------------------------------------
    
    public void tampilData(){
         DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("ID Penjualan");
        tbl.addColumn("Nama Barang");
        tbl.addColumn("Kode Barang");
        tbl.addColumn("Harga Barang");
        tbl.addColumn("Nama Pembeli");
        tbl.addColumn("Jumlah Barang");
        tbl.addColumn("Harga Total");
        tbl.addColumn("Pembayaran");
        tbl.addColumn("Kembali");
        
        Tabel_Toko.setModel(tbl); 
        try {
            Statement st = conn.getConnection().createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM tabel_penjualan");
            while (rs.next()) {
                tbl.addRow( new Object[] {
                    rs.getString("id_penjualan"),
                    rs.getString("nama_barang"),
                    rs.getString("kode_barang"),
                    rs.getString("harga_barang"),
                    rs.getString("nama_pembeli"),
                    rs.getString("jumlah_barang"),
                    rs.getString("total_harga"),
                    rs.getString("total_pembayaran"),
                    rs.getString("kembali"),
                });
                Tabel_Toko.setModel(tbl);
            }
         } catch (Exception e) {
            System.out.println(e);
        }
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Tabel = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        pilihbarang = new javax.swing.JComboBox<>();
        pembayaran = new javax.swing.JTextField();
        kembali = new javax.swing.JTextField();
        totalharga = new javax.swing.JTextField();
        jumlahbarang = new javax.swing.JTextField();
        namapembeli = new javax.swing.JTextField();
        hargabarang = new javax.swing.JTextField();
        kodebarang = new javax.swing.JTextField();
        bReset = new javax.swing.JButton();
        bHapus = new javax.swing.JButton();
        bSimpan = new javax.swing.JButton();
        bEdit = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabel_Toko = new javax.swing.JTable();
        bRefresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TOKO AIR MINERAL");
        jPanel1.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel4.setBackground(new java.awt.Color(102, 255, 204));
        java.awt.GridBagLayout jPanel4Layout = new java.awt.GridBagLayout();
        jPanel4Layout.columnWidths = new int[] {0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0};
        jPanel4Layout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        jPanel4.setLayout(jPanel4Layout);

        jLabel2.setText("Pilih barang");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel4.add(jLabel2, gridBagConstraints);

        jLabel3.setText("Kode barang");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel4.add(jLabel3, gridBagConstraints);

        jLabel4.setText("Harga barang");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel4.add(jLabel4, gridBagConstraints);

        jLabel5.setText("Nama pembeli");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel4.add(jLabel5, gridBagConstraints);

        jLabel6.setText("Jumlah barang");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel4.add(jLabel6, gridBagConstraints);

        jLabel7.setText("Total harga");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel4.add(jLabel7, gridBagConstraints);

        jLabel8.setText("Pembayaran");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 24;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel4.add(jLabel8, gridBagConstraints);

        jLabel9.setText("Kembali");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 26;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel4.add(jLabel9, gridBagConstraints);

        jLabel10.setText(":");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        jPanel4.add(jLabel10, gridBagConstraints);

        jLabel11.setText(":");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        jPanel4.add(jLabel11, gridBagConstraints);

        jLabel12.setText(":");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 12;
        jPanel4.add(jLabel12, gridBagConstraints);

        jLabel13.setText(":");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 14;
        jPanel4.add(jLabel13, gridBagConstraints);

        jLabel14.setText(":");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 22;
        jPanel4.add(jLabel14, gridBagConstraints);

        jLabel15.setText(":");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 24;
        jPanel4.add(jLabel15, gridBagConstraints);

        jLabel16.setText(":");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 26;
        jPanel4.add(jLabel16, gridBagConstraints);

        jLabel17.setText(":");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        jPanel4.add(jLabel17, gridBagConstraints);

        pilihbarang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--- Pilih Item ---", "AQUA", "CLEO", "CLUB", "LE MINERALE", "NESTLE" }));
        pilihbarang.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                pilihbarangItemStateChanged(evt);
            }
        });
        pilihbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihbarangActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel4.add(pilihbarang, gridBagConstraints);

        pembayaran.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                pembayaranFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 24;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel4.add(pembayaran, gridBagConstraints);

        kembali.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 26;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel4.add(kembali, gridBagConstraints);

        totalharga.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel4.add(totalharga, gridBagConstraints);

        jumlahbarang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jumlahbarangKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel4.add(jumlahbarang, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel4.add(namapembeli, gridBagConstraints);

        hargabarang.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel4.add(hargabarang, gridBagConstraints);

        kodebarang.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel4.add(kodebarang, gridBagConstraints);

        bReset.setText("Reset Form");
        bReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bResetActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 30;
        jPanel4.add(bReset, gridBagConstraints);

        bHapus.setText("Hapus");
        bHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHapusActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 30;
        jPanel4.add(bHapus, gridBagConstraints);

        bSimpan.setText("Simpan");
        bSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSimpanActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 30;
        jPanel4.add(bSimpan, gridBagConstraints);

        bEdit.setText("Edit");
        bEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 30;
        jPanel4.add(bEdit, gridBagConstraints);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Tabel.addTab("Form Barang", jPanel2);

        Tabel_Toko.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tabel_Toko.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabel_TokoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabel_Toko);

        bRefresh.setText("Refresh");
        bRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(bRefresh)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 693, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(bRefresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Tabel.addTab("Laporan Pembelian", jPanel3);

        jPanel1.add(Tabel, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void bResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bResetActionPerformed
        // TODO add your handling code here:
        pilihbarang.setSelectedIndex(0);
        kodebarang.setText("");
        hargabarang.setText("");
        namapembeli.setText("");
        jumlahbarang.setText("");
        totalharga.setText("");
        pembayaran.setText("");
        kembali.setText("");
    }//GEN-LAST:event_bResetActionPerformed

    private void Tabel_TokoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabel_TokoMouseClicked
        // TODO add your handling code here:
        bSimpan.setVisible(false);
        bEdit.setVisible(true);
       
        row = Tabel_Toko.getSelectedRow();
        
        pilihbarang.setSelectedItem((String) Tabel_Toko.getValueAt(row, 1));
        kodebarang.setText((String) Tabel_Toko.getValueAt(row, 2));
        namapembeli.setText((String) Tabel_Toko.getValueAt(row, 4));
        hargabarang.setText((String) Tabel_Toko.getValueAt(row, 3));
        jumlahbarang.setText((String) Tabel_Toko.getValueAt(row, 5));
        totalharga.setText((String) Tabel_Toko.getValueAt(row, 6));
        pembayaran.setText((String) Tabel_Toko.getValueAt(row, 7));
        kembali.setText((String) Tabel_Toko.getValueAt(row, 8));   
    }//GEN-LAST:event_Tabel_TokoMouseClicked

    
    private void pilihbarangItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_pilihbarangItemStateChanged
        // TODO add your handling code here:
    String barang =(String) pilihbarang.getSelectedItem();
        if (barang == "AQUA") {
            kodebarang.setText("AQU");
            hargabarang.setText("5000");
        } else if (barang == "CLEO") {
            kodebarang.setText("CLE");
            hargabarang.setText("7000");
        }else if (barang == "CLUB") {
            kodebarang.setText("CLU");
            hargabarang.setText("4000");
        }else if (barang == "LE MINERALE") {
            kodebarang.setText("LEM");
            hargabarang.setText("5000");
        }else if (barang == "NESTLE") {
            kodebarang.setText("NES");
            hargabarang.setText("8000");
        } else {
            kodebarang.setText("");
            hargabarang.setText("");
        }  
    }//GEN-LAST:event_pilihbarangItemStateChanged

    
    private void bSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSimpanActionPerformed
        // TODO add your handling code here:
        String idPemesanan = generateRandString(3);
        String query = "INSERT INTO tabel_penjualan VALUES("
                + "'" + idPemesanan +"', "
                + "'" + namapembeli.getText() +"', "
                + "'" + kodebarang.getText() +"', "
                + "'" + pilihbarang.getSelectedItem() +"', "
                + "'" + Integer.valueOf(hargabarang.getText()) +"', "
                + "'" + Integer.valueOf(jumlahbarang.getText()) +"', "
                + "'" + Integer.valueOf(totalharga.getText()) +"', "
                + "'" + Integer.valueOf(pembayaran.getText()) +"', "
                + "'" + Integer.valueOf(kembali.getText()) +"'"
                + ")";
        
        try{
            Statement st = conn.getConnection().createStatement();
            st.executeUpdate(query);
            st.close();
            JOptionPane.showMessageDialog(this, "data berhasil  disimpan");
            bResetActionPerformed(evt);
            bRefreshActionPerformed(evt);
            
        } catch (Exception e) {
             JOptionPane.showMessageDialog(this, "data gagal disimpan");
             System.out.println(e);
        }
    }//GEN-LAST:event_bSimpanActionPerformed

    private void bHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHapusActionPerformed
        // TODO add your handling code here:
        String query = "DELETE FROM tabel_penjualan WHERE tabel_penjualan ."
                + "id_penjualan =" + "'" + Tabel_Toko.getValueAt(row, 0) + "'";
        try {
            Statement st = conn.getConnection().createStatement();
            st.executeUpdate(query);
            st.close();
            JOptionPane.showMessageDialog(this, "Data berhasil dihapus");
            bRefreshActionPerformed(evt);
            
        } catch (Exception e) {
             JOptionPane.showMessageDialog(this, "Data gagal dihapus");
             System.out.println(e);
        }
    }//GEN-LAST:event_bHapusActionPerformed

    private void bRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRefreshActionPerformed
        // TODO add your handling code here:
        tampilData();
        bSimpan.setVisible(true);
        bEdit.setVisible(false);
        bResetActionPerformed(evt);
    }//GEN-LAST:event_bRefreshActionPerformed

    private void bEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditActionPerformed
        // TODO add your handling code here:
        String query = "UPDATE tabel_penjualan SET "
                + "nama_pembeli =       '" + namapembeli.getText() + "', "
                + "kode_barang =        '" + kodebarang.getText() + "', "
                + "nama_barang =        '" + pilihbarang.getSelectedItem()+ "', "
                + "harga_barang =       '" + hargabarang.getText() + "', "
                + "jumlah_barang =      '" + jumlahbarang.getText() + "', "
                + "total_harga =        '" + totalharga.getText() + "', "
                + "total_pembayaran =   '" + pembayaran.getText() + "', "
                + "kembali =            '" + kembali.getText() + "'"
                + "WHERE tabel_penjualan . id_penjualan = " + "'" 
                + Tabel_Toko.getValueAt(row, 0) + "';"
                ;
        
        try{
            Statement st = conn.getConnection().createStatement();
            st.executeUpdate(query);
            st.close();
            JOptionPane.showMessageDialog(this, "Data berhasil diperbarui");
            bRefreshActionPerformed(evt);
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, "Data gagal diperbarui");
            System.out.println(e);
        }
    }//GEN-LAST:event_bEditActionPerformed

    private void jumlahbarangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jumlahbarangKeyReleased
        // TODO add your handling code here:
                try {
            String JmlBarang = jumlahbarang.getText();int HargaBarang = Integer.parseInt(hargabarang.getText());
            int TotalHarga = HargaBarang * Integer.parseInt(jumlahbarang.getText());
            totalharga.setText(String.valueOf(TotalHarga));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Inputan harus angka", 
                    "Error", JOptionPane.ERROR_MESSAGE);
        } 
    }//GEN-LAST:event_jumlahbarangKeyReleased

    private void pembayaranFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pembayaranFocusLost
        // TODO add your handling code here:
            int TotalHarga = Integer.parseInt(totalharga.getText());
        int TotalBayar = Integer.parseInt(pembayaran.getText());
        int Kembali = TotalBayar - TotalHarga;
        if (Kembali < 0) {
            JOptionPane.showMessageDialog(null, "Uang Pembayaran Anda Kurang", 
                    "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            kembali.setText(String.valueOf(Kembali));
        }
    }//GEN-LAST:event_pembayaranFocusLost

    private void pilihbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihbarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pilihbarangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TokoAir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TokoAir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TokoAir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TokoAir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TokoAir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Tabel;
    private javax.swing.JTable Tabel_Toko;
    private javax.swing.JButton bEdit;
    private javax.swing.JButton bHapus;
    private javax.swing.JButton bRefresh;
    private javax.swing.JButton bReset;
    private javax.swing.JButton bSimpan;
    private javax.swing.JTextField hargabarang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jumlahbarang;
    private javax.swing.JTextField kembali;
    private javax.swing.JTextField kodebarang;
    private javax.swing.JTextField namapembeli;
    private javax.swing.JTextField pembayaran;
    private javax.swing.JComboBox<String> pilihbarang;
    private javax.swing.JTextField totalharga;
    // End of variables declaration//GEN-END:variables
Koneksi conn;
int row;
}
